version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "7001:7000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - DATABASE_NAME=image_moderation
      - SIGHTENGINE_API_USER=86502181
      - SIGHTENGINE_API_SECRET=DFqvSFjWzDx3gGcBUaYCCf8KxEh3JyLt
    depends_on:
      - mongo
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:7001
    command: ["serve", "-s", "build", "-l", "3000"]
    depends_on:
      - backend
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--quiet", "--logpath=/dev/null", "--bind_ip_all"]
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: 